name: actions-setup
on:
  push:
jobs:
  job_one:
    name: Run-Tests
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            gradle build
            gradle test --parallel
  
